// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(chatName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"player-view\" hx-ext=\"sse\" sse-connect=\"/events?role=player\"><header class=\"topbar\"><h1>Dungeon Revealer</h1><nav><a href=\"/logout\">Logout</a></nav></header><div class=\"content player-layout\"><div class=\"map-area\" hx-get=\"/maps/active\" hx-trigger=\"load\" hx-target=\"this\"><p class=\"muted\">Waiting for the DM to select a map...</p></div><aside class=\"sidebar\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ChatPanel(chatName).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"sidebar-section\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = NotesPanel(false).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><div id=\"notes-content\"></div></aside></div><div id=\"sse-chat\" sse-swap=\"chatMessage\" hx-target=\"#chat-messages\" hx-swap=\"beforeend\"></div><div hx-trigger=\"sse:fogUpdate\" style=\"display:none\"></div><div hx-trigger=\"sse:tokenUpdate\" style=\"display:none\"></div><div hx-trigger=\"sse:notesUpdated\" hx-get=\"/notes\" hx-target=\"#notes-list\" style=\"display:none\"></div><script>\n\t\t\t\tdocument.body.addEventListener('sse:fogUpdate', function(e) {\n\t\t\t\t\tvar view = document.getElementById('player-map-view');\n\t\t\t\t\tvar currentMapId = view ? view.dataset.mapId : '';\n\t\t\t\t\tvar pushedMapId = e.detail && e.detail.data ? e.detail.data : '';\n\t\t\t\t\tif (!currentMapId || (pushedMapId && pushedMapId !== currentMapId)) {\n\t\t\t\t\t\tvar mapArea = document.querySelector('.map-area');\n\t\t\t\t\t\tif (mapArea) htmx.ajax('GET', '/maps/active', {target: mapArea, swap: 'innerHTML'});\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t</script></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Player").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
